#!/bin/bash
#my attempt at a color example script.

t="text" 
esc="\033["

# echo -e "\n       40m     41m     42m     43m     44m     45m     46m     47m";

for fg in '30m' '31m' '32m' '33m' '34m' '35m' '36m';
    do echo ""   #-en " $fg " 
    for bg in '40m' '41m' '42m' '43m' '44m' '45m' '46m';
        do echo -en " $esc$fg$esc$bg $t "
    done
done
